#!/bin/bash

# innacurate at anything but 10 wide weird math errors in bash that i couldn't figure out
# lack of floats not helpful. needs to be redone in different language to be more useful

width=10
x=$((100/$width))
interval=1

create_lines() {

  cpu_lines=$(round $cpu_info/$x 0)

  lines=""

  for (( i = 0; i < $width; i++ )); do
    if [[ "$i" < "$cpu_lines" ]]; then
      lines="$lines|"
    else
      lines="$lines "
    fi
  done
} 

round() { 
echo $(printf %.$2f $(echo "scale=$2;(((10^$2)*$1)+0.5)/(10^$2)" | bc)) 
};

if [[ $OSTYPE =~ darwin* ]]; then
  cpu_info=$(iostat -n0 -c2 | tail -n1 | awk '{print $1 + $2}')
  # load=$(iostat -n0 -c1 | tail -n1 | cut -d' ' -f8,9,10)
elif [[ $OSTYPE =~ linux* ]]; then
  cpu_info=($(vmstat 1 ${interval} | tail -n1 | awk '{print $13 " " $14}'))
  # load=$(awk '{print $1,$2,$3}' /proc/loadavg)
fi

create_lines
echo "[${lines}] ${cpu_info}%"