#!/usr/bin/env python
# -*- coding: utf-8 -*-

import psutil

def make_dashes(perc):
    dashes = "⋮" * int((float(perc) / 10))
    empty_space = " " * (10 - len(dashes))
    return dashes, empty_space

def get_cpu():
    usedcpu = psutil.cpu_percent(interval=0.1)
    
    dashes, empty_space = make_dashes(usedcpu)
    line = "[%s%s] %s%%" % (
        dashes, empty_space,
        usedcpu,
    )

    return line

def main():
    try:
        print get_cpu()
    except (KeyboardInterrupt, SystemExit):
        pass

if __name__ == '__main__':
    main()
